# LF (144)
*z,=open(0,'rb');u=sum;print(u((u({*a[(l:=len(a)//2):]}&{*a[:l]})-96)%58for a in z),u((u({*b}&{*c}&{*d})-106)%58for b,c,d in zip(*3*[iter(z)])))
# CR (144)
*z,=open(0,'rb');u=sum;print(u((u({*a[(l:=len(a)//2):]}&{*a[:l]})-96)%58for a in z),u((u({*b}&{*c}&{*d})-109)%58for b,c,d in zip(*3*[iter(z)])))
# CRLF (146)
*z,=open(0,'rb');u=sum;print(u((u({*a[(l:=len(a)//2-1):]}&{*a[:l]})-96)%58for a in z),u((u({*b}&{*c}&{*d})-119)%58for b,c,d in zip(*3*[iter(z)])))
# xplatform (156)
z=open(0,'rb').read().split();u=sum;print(u((u({*a[(l:=len(a)//2):]}&{*a[:l]})-96)%58for a in z),u((u({*b}&{*c}&{*d})-96)%58for b,c,d in zip(*3*[iter(z)])))
# xplatform one loop (161)
u=sum;print(u(u((u({*a[(l:=len(a)//2):]}&{*a[:l]})-96)%58for a in(b,c,d))+(u({*b}&{*c}&{*d})-96)%58*1j for b,c,d in zip(*3*[iter(open(0,'rb').read().split())])))
# encoded
# LF (97)
exec(bytes("稪㴬灯湥〨✬扲⤧画猽浵瀻楲瑮用⠨⡵⩻孡氨㴺敬⡮⥡⼯⤲崺♽⩻孡氺絝⴩㘹┩㠵潦⁲⁡湩稠Ⱙ⡵用笨截♽⩻絣符搪⥽ㄭ㘰┩㠵潦⁲ⱢⱣ⁤湩稠灩⨨⨳楛整⡲⥺⥝⤩",'u16')[2:])
# CR (97)
exec(bytes("稪㴬灯湥〨✬扲⤧画猽浵瀻楲瑮用⠨⡵⩻孡氨㴺敬⡮⥡⼯⤲崺♽⩻孡氺絝⴩㘹┩㠵潦⁲⁡湩稠Ⱙ⡵用笨截♽⩻絣符搪⥽ㄭ㤰┩㠵潦⁲ⱢⱣ⁤湩稠灩⨨⨳楛整⡲⥺⥝⤩",'u16')[2:])
# CRLF (98)
exec(bytes('稪㴬灯湥〨✬扲⤧画猽浵瀻楲瑮用⠨⡵⩻孡氨㴺敬⡮⥡⼯ⴲ⤱崺♽⩻孡氺絝⴩㘹┩㠵潦⁲⁡湩稠Ⱙ⡵用笨截♽⩻絣符搪⥽ㄭ㤱┩㠵潦⁲ⱢⱣ⁤湩稠灩⨨⨳楛整⡲⥺⥝⤩','u16')[2:])
# xplatform (103)
exec(bytes("㵺灯湥〨✬扲⤧爮慥⡤⸩灳楬⡴㬩㵵畳㭭牰湩⡴⡵用笨愪⡛㩬氽湥愨⼩㈯㨩絝符愪㩛嵬⥽㤭⤶㔥昸牯愠椠⁮⥺甬⠨⡵⩻絢符挪♽⩻絤⴩㘹┩㠵潦⁲ⱢⱣ⁤湩稠灩⨨⨳楛整⡲⥺⥝⤩",'u16')[2:])
# xplatform one loop (106)
exec(bytes("㵵畳㭭牰湩⡴⡵⡵用笨愪⡛㩬氽湥愨⼩㈯㨩絝符愪㩛嵬⥽㤭⤶㔥昸牯愠椠⡮ⱢⱣ⥤⬩用笨截♽⩻絣符搪⥽㤭⤶㔥⨸樱映牯戠挬搬椠⁮楺⡰㌪嬪瑩牥漨数⡮ⰰ爧❢⸩敲摡⤨献汰瑩⤨崩⤩ ",'u16')[2:])